### ISSUE TITLE
Could it be extended to syntax objects?

### ISSUE THREAD

**Issue by wilbowma** [stamourv/sexp-diff#4]
I'm using this to compute diffs between `racketgrammar`s, except a bunch of useful information is lost in converting to datums.

**Comment by wilbowma** [comment]
This answer is "yes", although I'm doing an imperfect job of preserving properties and source location information is weird when it might come from two different places.

https://github.com/wilbowma/sexp-diff/commit/5998a987d48add3d19b4ab01a6482b19b78d01d1

**Comment by stamourv** [comment]
Cool. I'm happy to accept a PR.
Your commit message mentions a change in interface; is it backwards compatible?

**Comment by wilbowma** [comment]
I generalized it slightly, but could make it backwards compatible. I also want to figure how how to merge source locations in a more sensible way (at least enough in a way that works for my use case), and abstract put some copy-pasted code. I’ll submit a PR then.

--
