### ISSUE TITLE
`(require scribble/example)` breaks this for Racket 6.3

### ISSUE THREAD

**Issue by greghendershott** [stamourv/sexp-diff#6]
Commit 5d68924 adds a `(require scribble/example)`. This seems not to work in Racket 6.3 (just work in later versions).

I have Travis CI do monthly "cron" builds, which catches changed/broken dependencies. I recently noticed [this failed a few days ago](https://travis-ci.com/github/greghendershott/markdown/jobs/365838398#L275).

I suppose I could bump `markdown` and `frog` from 6.3 to 6.4 (and hope nothing using `markdown`, e.g. `pollen`, still needs/wants 6.3). But I figured I'd ask here, first. I don't know if `scribble/example` is critical, or not? If critical: I don't know if `scribble/example` needs Racket 6.4, or, could `scribble/example` be pulled in explicitly in `deps` in your `info.rkt` so it works even in 6.3 (maybe)?

**Comment by stamourv** [comment]
Hi Greg, thanks for the report!

I wouldn't say scribble/example is *critical*, but I think it's a useful addition here.

I could add a version exception for 6.3 that points to a branch where the docs don't have these examples. Does that sound reasonable?

I'm intrigued by your suggestion of pulling in `scribble/example` explicitly in `deps`. I don't remember the history, but I don't think `scribble/example` was ever available as a separate package. I think it just got added to `scribble-lib` around 6.4. Can you elaborate on the solution you had in mind?

**Comment by greghendershott** [comment]
> I could add a version exception for 6.3 that points to a branch where the docs don't have these examples. Does that sound reasonable?

That sounds reasonable -- thanks!!

---

p.s.

> I'm intrigued by your suggestion of pulling in scribble/example explicitly in deps. I don't remember the history, but I don't think scribble/example was ever available as a separate package. I think it just got added to scribble-lib around 6.4. Can you elaborate on the solution you had in mind?

Sorry I tried to use words like "could" and "maybe" to signal that I wasn't offering a definite solution --- just a hand-wavy idea.

**Comment by stamourv** [comment]
Gotcha. I'll do that.

Re suggestion: gotcha. My pkg game is pretty rusty, so I thought you may know something that I don't. ;)

Thanks again!

**Comment by stamourv** [comment]
Closed by 5736a70c905474c26e486e71bb00fec29a434114.
